name: kavach_hackvortex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  image_picker_web: ^3.0.6
  path_provider: ^2.0.15
  intl: ^0.20.0
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.1.0

  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  sliding_up_panel: ^2.0.0+1

  http: ^1.0.0
  dialog_flowtter: ^0.2.0-nullsafety.0
  flutter_dotenv: ^5.0.2

  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  flutter_local_notifications: ^17.2.3

  pdf: ^3.8.4
  open_file: ^3.3.2
  debounce_throttle: ^2.0.0

  url_launcher: ^6.3.1
  telephony: ^0.2.0

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  fluttertoast: ^8.2.12
  google_sign_in: ^6.3.0

  shared_preferences: ^2.5.3
  google_fonts: ^4.0.4
  syncfusion_flutter_charts: ^29.1.39
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^4.0.1
  file_picker: ^10.1.2

  cloud_firestore: ^5.6.7
  firebase_storage: ^12.3.4
  
  video_thumbnail: ^0.5.3
  video_player: ^2.9.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/SHIELD_LOGO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO.jpeg
    - assets/images/LOGO-NOBG.png
    - assets/images/SHIELD_LOGO.png
    - assets/images/SHIELD_LOGO-NOBG.png
    - assets/images/profile.jpg

    - assets/.env
    - assets/dialog_flow_auth.json
    - assets/map_style_dark.json
    - assets/incidents_augmented.json

    - assets/icons/home.png
    - assets/icons/home_active.png
    - assets/icons/map.png
    - assets/icons/map_active.png
    - assets/icons/live-streaming.png
    - assets/icons/live-streaming_active.png
    - assets/icons/chat.png
    - assets/icons/chat_active.png
    - assets/icons/user.png
    - assets/icons/user_active.png
    - assets/icons/file.png
    - assets/icons/file_active.png
    - assets/icons/news.png
    - assets/icons/news_active.png

    - assets/fonts/Roboto-Regular.ttf