// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8IYJorSeDfQro5zBoB2glRmPSnTZuTgI',
    appId: '1:28593247285:web:aef0fbfe8bb6ff6874cd7c',
    messagingSenderId: '28593247285',
    projectId: 'kavach-c9d5b',
    authDomain: 'kavach-c9d5b.firebaseapp.com',
    storageBucket: 'kavach-c9d5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVE6d-tqqmb1aL4N2OI8a0JKS6_VZYEpU',
    appId: '1:28593247285:android:33d3fcf6a6d881f974cd7c',
    messagingSenderId: '28593247285',
    projectId: 'kavach-c9d5b',
    storageBucket: 'kavach-c9d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj51-cOGw0MajGmChHyRnHxc_hacdQmRU',
    appId: '1:28593247285:ios:e1cccb8b2e91cfaf74cd7c',
    messagingSenderId: '28593247285',
    projectId: 'kavach-c9d5b',
    storageBucket: 'kavach-c9d5b.firebasestorage.app',
    androidClientId:
        '28593247285-ebur07gg8r3vh58n09od9crv7elag84c.apps.googleusercontent.com',
    iosClientId:
        '28593247285-aagtr369vh3hk1c8jh3arsijf521pj6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj51-cOGw0MajGmChHyRnHxc_hacdQmRU',
    appId: '1:28593247285:ios:e1cccb8b2e91cfaf74cd7c',
    messagingSenderId: '28593247285',
    projectId: 'kavach-c9d5b',
    storageBucket: 'kavach-c9d5b.firebasestorage.app',
    androidClientId:
        '28593247285-ebur07gg8r3vh58n09od9crv7elag84c.apps.googleusercontent.com',
    iosClientId:
        '28593247285-aagtr369vh3hk1c8jh3arsijf521pj6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8IYJorSeDfQro5zBoB2glRmPSnTZuTgI',
    appId: '1:28593247285:web:4f5bc1f8af7071fb74cd7c',
    messagingSenderId: '28593247285',
    projectId: 'kavach-c9d5b',
    authDomain: 'kavach-c9d5b.firebaseapp.com',
    storageBucket: 'kavach-c9d5b.firebasestorage.app',
  );
}
